### ISSUE TITLE
[FEATURE] Please update

### ISSUE THREAD

**Issue by Acat1234** [yyon/grapplemod#139]
I cant use the required forge version because it breaks my game so can it get updated to the latest forge version?

**Comment by KavisCorea** [comment]
Im going to one up this; the forge version required is a bit old and some of the mods I want/need to use require the newer version (specifically the recommended 47.3.0). So a compatibility update would be extremely appreciated!

**Comment by Nyfaria** [comment]
@KavisCorea @Acat1234 Sorry but no. We can't in good faith continue to support forge.

**Comment by Crabsnake** [comment]
If Neoforge ever does update, would a fix be implemented? it's a quite prominent issue.

**Comment by Nyfaria** [comment]
> If Neoforge ever does update, would a fix be implemented? it's a quite prominent issue.

It's a non-issue, using 47.1.3 fixes it. forge broke something, im not fixing forge.
Why would it stay broken when moving to neoforge where things aren't broken?

**Comment by superon** [comment]
update the information on the modpage then to say something along the lines of "this mod doesn't work with versions of Forge past 47.1.3 and i'm actively disinterested in creating a version of the mod that's compatible because i think forge is broken"

this will prevent plenty of people from both posting here in issues and from initially downloading it and wasting hours playtesting only to find it's a forge issue, seems like a simple courtesy.

**Comment by yyon** [comment]
It already says it on the mod page, the first line in large font

**Comment by superon** [comment]
https://modrinth.com/mod/grappling-hook-mod ;)
