### ISSUE TITLE
several items not appearing when using RLcraft

### ISSUE THREAD

**Issue by Clanof1** [yyon/grapplemod#65]
the motorized, dual wield, and ender hook, are not appearing but the modifications for them are showing in the creative inventory as well as the normal hook and ender staff showing up with their modifications as well. is half of the mod not compatible with RLcraft mod pack or did i install it wrong. RLcraft has a grapple hook mod in it but it uses a fishing hook style rope and only allows vertical ascension and not swinging. only the standard grapple hook is craftable however. even the items that appear in creative are uncraftable

**Comment by Clanof1** [comment]
the long fall boots also DO appear in the menu

**Comment by yyon** [comment]
I guess I never updated the mod page to reflect this but in the most recent version of the mod, the different types of grappling hook aren't craftable, you have to use the modification block + upgrades to do it instead. If you use the modification block+upgrades, you can get the different types of grappling hooks (and also have some more control over them). I was planning on re-adding crafting recipes for convenience in future versions, but for right now the modifier block is the only way. So no, you didn't mess up installing the mod. Also they don't show up in creative inventory or in jei or stuff because all grappling hooks are the same "item", just with lots of data stored about how they are modified, so you have to use the modifier block in creative mode too for now unfortunately.

**Comment by Clanof1** [comment]
> I guess I never updated the mod page to reflect this but in the most recent version of the mod, the different types of grappling hook aren't craftable, you have to use the modification block + upgrades to do it instead. If you use the modification block+upgrades, you can get the different types of grappling hooks (and also have some more control over them). I was planning on re-adding crafting recipes for convenience in future versions, but for right now the modifier block is the only way. So no, you didn't mess up installing the mod. Also they don't show up in creative inventory or in jei or stuff because all grappling hooks are the same "item", just with lots of data stored about how they are modified, so you have to use the modifier block in creative mode too for now unfortunately.

Cool. thank you
